### ISSUE TITLE
Not Recognized Commands

### ISSUE THREAD

**Issue by thecatgamer137** [YTP-Plus/YTPPlusStudio#2]
There is a problem with ytp+ "'git' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
'npm' is not recognized as an internal or external command,
operable program or batch file."

**Comment by TeamPopplio** [comment]
Hi, this is a [YTPPlus/YTPPlusCLI](https://github.com/YTP-Plus/YTPPlusCLI) issue as ytp+ studio does not generate videos on its own.

**Comment by TeamPopplio** [comment]
I'm sorry, my mistake.

**Comment by TeamPopplio** [comment]
This issue revolves around the installation process. To bypass installation, please install [Git for Windows](https://gitforwindows.org/) and [NodeJS](https://nodejs.org/) with its additional tools and re-run the installer to proceed. This is a temporary fix and I'll work to fix this issue in the meantime.

**Comment by TeamPopplio** [comment]
Fixed in 73f08ebf4d27ec2a5694af7ad308c748bed280e4 due to removal of auto installers.
