### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Gabriel6544** [YTP-Plus/YTPPlusStudio#4]
So when I opened the exe file, after around 3 seconds a error popped up saying it can't find file 'nood' how do I fix this

**Comment by TeamPopplio** [comment]
Hi, I'm not sure how you got here without going to the github.io landing page first but you need to install the prerequisites as per https://ytp-plus.github.io/#/articles/installing and run the launcher.

If there are any more issues, please contact me on the Discord server or directly via Kiwifruit#2003.

Thank you.
