### ISSUE TITLE
Project not active anymore?

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [YTP-Plus/YTPPlusStudio#5]
I have been using YTP+ for a year. However, when I check your program's latest release, it still stays on version 1.3.3. Please continue updating YTP+ Studio!

**Comment by nuppington-bit** [comment]
Both me and @TeamPopplio have been trying to divide our attention between this project and our other project which can be found at https://github.com/Tidal-Members/ and has been updated a lot more. @TeamPopplio has been planning something new that will be similar to ytp+ studio. We aren't happy with the amount of people coming into our server to get help, and we want to create something that will be much easier to use by anyone, not just people in our server.

**Comment by nuppington-bit** [comment]
Keep in mind we are not abandoning ytp+ studio (at least not yet). However, I will not be updating it for a while due to computer troubles, but I can't speak for @TeamPopplio.

**Comment by NanaMizukiAnother7** [comment]
Your computer has troubles?

**Comment by nuppington-bit** [comment]
Yes, each time I turn it on it beeps three times then stops, then beeps again. I will be attempting to switch over to a different PC, but I need a VGA cable first.

**Comment by TeamPopplio** [comment]
Hi, I'm currently in the planning stages for Super YTP++, an update for YTP++ that is to replace studio and cli due to developmental difficulties with Lua and node.js.

It is due to have a server booster, github contributor, and skilled author (discord roles) exclusive beta near the end of August.

Hope this clears things up for the future of YTP+ and it's maintenance.

**Comment by NanaMizukiAnother7** [comment]
Super YTP++? The newer look for YTP++?

**Comment by KiwifruitDev** [comment]
This repository is no longer supported.
See: [YTP+++](https://github.com/YTP-Plus/YTPPlusPlusPlus)
